In [8]:
import numpy as np
import pandas as pd

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


,0,1,2,3,4
0,0.000000,0.034483,0.068966,0.103448,0.137931
1,0.172414,0.206897,0.241379,0.275862,0.310345
2,0.344828,0.379310,0.413793,0.448276,0.482759
3,0.517241,0.551724,0.586207,0.620690,0.655172
4,0.689655,0.724138,0.758621,0.793103,0.827586
5,0.862069,0.896552,0.931034,0.965517,1.000000


In [33]:
input_data  = np.linspace(0, 300, 30).reshape(-1, 5)
output_data = (input_data)
output_data = np.array([np.sum(i)/5 for i in output_data])

input_data = pd.DataFrame(input_data)
output_data = pd.Series(output_data)


In [46]:
from model.scn import SCN_III

scn = SCN_III()
scn.fit(input_data, output_data)

In [47]:
scn.predict(input_data)

array([ 20.69010878,  72.41164883, 124.14207406, 175.85796915,
       227.58828728, 279.30991189])

In [48]:
output_data

0     20.689655
1     72.413793
2    124.137931
3    175.862069
4    227.586207
5    279.310345
dtype: float64

In [7]:
output_data

array([0.06896552, 0.24137931, 0.4137931 , 0.5862069 , 0.75862069,
       0.93103448])

In [45]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [7]:
pd.DataFrame({'date': dt_range})

,date
0,2023-01-01
1,2023-01-02
2,2023-01-03
3,2023-01-04
4,2023-01-05
5,2023-01-06
6,2023-01-07
7,2023-01-08
8,2023-01-09
9,2023-01-10
